title: Probus Production
include: [_pages,_posts]
markdown: kramdown
url: https://malikkurosaki.github.io/probus_production/
# plugins:
#   - jekyll-feed
#   - jekyll-paginate
#   - jekyll-seo-tag
#   - jekyll-toc
paginate: 20
collections:
  _pages:
    output: true
  _posts:
    output: true