title: Probus Production
include: [_pages,_posts]
markdown: kramdown
url: https://malikkurosaki.github.io/probus_production/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-toc
toc:
  min_level: 1
  max_level: 6
  no_toc_section_class: no_toc_section
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-
paginate: 20
theme: minima
favicon: "favicon.png"
icon: "favicon.png"